
truncate price_sub_categories
truncate zim_events;

INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('1', '1', '1', '5km Race', '125.0000', '0.0000', '5', '2', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('2', '1', '1', '10km Race', '125.0000', '0.0000', '5', '1000', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('3', '2', '1', 'VIP 1000', '1.0000', '100.0000', '5', '2', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('4', '2', '1', 'General 500', '1.0000', '50.0000', '5', '1', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('5', '3', '1', 'General 500', '1.0000', '50.0000', '5', '1', 'sold_out', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('6', '4', '1', 'General 500', '500.0000', '50.0000', '5', '1000', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('7', '51', '1', 'General 500', '500.0000', '50.0000', '5', '1000', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('8', '6', '1', 'General 500', '500.0000', '50.0000', '5', '1000', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('9', '7', '1', 'General 500', '500.0000', '50.0000', '5', '1000', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('10', '7', '1', 'Older runner', '1.0000', '150.0000', '5', '1000', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('11', '1', '1', '21km Race', '200.0000', '0.0000', '5', '1000', 'sale', NULL, NULL);
INSERT INTO `eventszim`.`price_sub_categories` (`id`, `event_id`, `category_id`, `description`, `price_zwl`, `price_usd`, `max_tickets`, `quantity`, `status`, `created_at`, `updated_at`) VALUES ('12', '1', '1', '53km Race', '200.0000', '0.0000', '5', '1000', 'sale', NULL, NULL);


INSERT INTO `eventszim`.`zim_events` (`id`, `event_type_id`, `catergory_id`, `event_name`, `start_date`, `end_date`, `popular_rank`, `created_at`, `updated_at`) VALUES ('1', '1', '1', 'PPC Marathon', '2020-03-28 06:00:00', '2020-03-28 06:00:00', '1.0000', NULL, NULL);
INSERT INTO `eventszim`.`zim_events` (`id`, `event_type_id`, `catergory_id`, `event_name`, `start_date`, `end_date`, `popular_rank`, `created_at`, `updated_at`) VALUES ('2', NULL, '1', 'Madirirano', '2019-12-25 00:00:00', '2019-12-26 00:00:00', '2.0000', NULL, NULL);
INSERT INTO `eventszim`.`zim_events` (`id`, `event_type_id`, `catergory_id`, `event_name`, `start_date`, `end_date`, `popular_rank`, `created_at`, `updated_at`) VALUES ('3', NULL, '1', 'Jah Prayza', '2020-03-21 00:00:00', '2020-03-21 00:00:00', '2.0000', NULL, NULL);
INSERT INTO `eventszim`.`zim_events` (`id`, `event_type_id`, `catergory_id`, `event_name`, `start_date`, `end_date`, `popular_rank`, `created_at`, `updated_at`) VALUES ('4', NULL, '1', 'Winky D', '2020-03-21 00:00:00', '2020-03-21 00:00:00', '2.0000', NULL, NULL);
INSERT INTO `eventszim`.`zim_events` (`id`, `event_type_id`, `catergory_id`, `event_name`, `start_date`, `end_date`, `popular_rank`, `created_at`, `updated_at`) VALUES ('5', NULL, '1', 'Zifm Judgement', '2019-12-25 00:00:00', '2019-12-26 00:00:00', '2.0000', NULL, NULL);
INSERT INTO `eventszim`.`zim_events` (`id`, `event_type_id`, `catergory_id`, `event_name`, `start_date`, `end_date`, `popular_rank`, `created_at`, `updated_at`) VALUES ('6', NULL, '1', 'Star Fm Awards', '2019-12-25 00:00:00', '2019-12-26 00:00:00', '2.0000', NULL, NULL);
INSERT INTO `eventszim`.`zim_events` (`id`, `event_type_id`, `catergory_id`, `event_name`, `start_date`, `end_date`, `popular_rank`, `created_at`, `updated_at`) VALUES ('7', '1', '1', 'Econet Marathon', '2020-03-21 00:00:00', '2020-03-21 00:00:00', '1.0000', NULL, NULL);
